Prototype/prototype/Login/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from prototype import conn
from prototype.forms import LoginForm
from flask_login import login_user, current_user, logout_user
from prototype.models import select_Patient, get_History, get_Diagnoses, get_Active_Prescriptions, insert_New_Renewed_Prescription, update_Active_Prescription

Login = Blueprint('Login', __name__)

@Login.route("/receptfornyelse")
def receptfornyelse():
    p = get_Active_Prescriptions(current_user.get_id(), conn)
    return render_template('receptfornyelse.html', percs=p)

@Login.route('/renew/<med_name>/<med_conc>')
def renew(med_name, med_conc):
    insert_New_Renewed_Prescription(current_user.get_id(), med_name, med_conc, conn)
    p = get_Active_Prescriptions(current_user.get_id(), conn)
    flash('Receptfornyelse godkendt.', 'success')
    return redirect(url_for('.receptfornyelse', percs=p))

@Login.route("/meddelser")
def meddelelser():
    return render_template('meddelelser.html')

@Login.route("/aftaler")
def aftaler():
    return render_template('aftaler.html')

@Login.route("/historik")
def historik():
    h = get_History(current_user.get_id(), conn)
    return render_template('historik.html', history=h)

@Login.route("/sundhedsdata")
def sundhedsdata():
    d = get_Diagnoses(current_user.get_id(), conn)
    return render_template('sundhedsdata.html', diagnoses=d)

@Login.route("/fahjaelp")
def fahjaelp():
    return render_template('fahjaelp.html')

@Login.route("/")
@Login.route("/profil")
def profil():
    if not current_user.is_authenticated:
        return redirect(url_for('Login.login'))
    return render_template('profil.html')

@Login.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('Login.profil'))
    form = LoginForm()
    if form.validate_on_submit():
        user = select_Patient(form.id.data, conn)
        if user is not None and user.password == form.password.data:
            login_user(user)
            flash('Login successful.', 'success')
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('Login.profil'))
        else:
            flash('Login Unsuccessful. Please check identifier and password', 'danger')
    return render_template('login.html', title='Login', form=form)

@Login.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('Login.login'))

Prototype/prototype/Main/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from prototype import conn
from prototype.Main.forms import LoginForm
from flask_login import login_user, current_user, logout_user
from prototype.models import select_Patient, get_History, get_Diagnoses, get_Active_Prescriptions, \
    insert_New_Renewed_Prescription, join_prescription_diagnose

Main = Blueprint('Main', __name__)

@Main.route("/receptfornyelse")
def receptfornyelse():
    p = get_Active_Prescriptions(current_user.get_id(), conn)
    return render_template('receptfornyelse.html', percs=p)

@Main.route('/renew/<med_name>/<med_conc>/<illness>')
def renew(med_name, med_conc, illness):
    insert_New_Renewed_Prescription(current_user.get_id(), med_name, med_conc, illness, conn)
    p = get_Active_Prescriptions(current_user.get_id(), conn)
    flash('Receptfornyelse godkendt.', 'success')
    return redirect(url_for('.receptfornyelse', percs=p))

@Main.route("/historik")
def historik():
    h = get_History(current_user.get_id(), conn)
    return render_template('historik.html', history=h)

@Main.route("/medicinkort")
def medicinkort():
    j = join_prescription_diagnose(current_user.get_id(), conn)
    return render_template('medicinkort.html', joined=j)

@Main.route("/")
@Main.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('Main.receptfornyelse'))
    form = LoginForm()
    if form.validate_on_submit():
        user = select_Patient(form.id.data, conn)
        if user is not None and user.password == form.password.data:
            login_user(user)
            flash('Login successful.', 'success')
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('Main.receptfornyelse'))
        else:
            flash('Login Unsuccessful. Please check identifier and password', 'danger')
    return render_template('login.html', title='Login', form=form)

@Main.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('Main.login'))

Prototype/prototype/templates/historik.html
{% extends "layout.html" %}
{% block content %}
    {% if current_user.is_authenticated %}
    
    <h1 style="border-bottom: 1px solid #000; padding-bottom: 15px; color: #02376a; font-size: 36px;">Historik</h1>

    {% for h in history %}
    <div class="modul">
        <ul style="float:left; text-align:left;">
            <li>Medicin: {{ h.medicine_name }}</li>
            <li>Styrke: {{ h.medicine_concentration }}</li>
            <li>Sidst fornyet d. {{ h.renewal }}</li>
            <li>Behandling for: {{ h.illness }}</li>
        </ul>
    </div>
    {% endfor %}

    {% endif %}
{% endblock content %}

Prototype/prototype/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css', v=0.05) }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/progress.css') }}">

    {% if title %}
        <title>UIS Prototype - {{ title }}</title>
    {% else %}
        <title>UIS Prototype</title>
    {% endif %}
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>

</head>
<body>
<div class="app" :class="[confirmed? 'app__green' : '']">
    <main role="main" class="container">
      <div class="row">
        <div class="content_wrap"> 
            <div class="content">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          <div class="logosjov"><a href="#"><img src="{{ url_for('static', filename='images/loginlogo.png') }}"></a></div>
          {% if current_user.is_authenticated %}
          <div class="menu">
              <li><a href="#"><img src="{{ url_for('static', filename='images/name.png') }}" class="menu_image">Navn</a></li>
              <li><a href="#"><img src="{{ url_for('static', filename='images/messages.png') }}" class="menu_image">Meddelser</a></li>
              <li><a href="#"><img src="{{ url_for('static', filename='images/appoint.png') }}" class="menu_image">Aftaler</a></li>
              <li><a href="#"><img src="{{ url_for('static', filename='images/sd.png') }}" class="menu_image">Sundhedsdata</a></li>
              <li class="dropdown">
                <a href="#" class="nav-item nav-link dropdown-toggle" data-toggle="dropdown"><img src="{{ url_for('static', filename='images/doc.png') }}" class="menu_image">Receptfornyelse<b class="caret"></b></a>
                <ul class="dropdown-menu">
                   <li class="divider"></li>
                   <li><a href="{{ url_for('Main.receptfornyelse') }}" class="nav-item nav-link" style="float: left;">Forny recept</a></li>
                   <li><a href="{{ url_for('Main.medicinkort') }}" class="nav-item nav-link">Medicin kort</a></li>
                   <li><a href="{{ url_for('Main.historik') }}" class="nav-item nav-link">Historik</a></li>
                </ul>
              </li>
              <li><a href="#"><img src="{{ url_for('static', filename='images/avatar.png') }}" class="menu_image">Profil</a></li>
              <li><a href="#"><img src="{{ url_for('static', filename='images/info.png') }}" class="menu_image">Få hjælp</a></li>
              <a class="nav-item nav-link" style="font-size: 12px; padding:0;" href="{{ url_for('Main.logout') }}">Log ud af minsundhedsplatform.dk</a>
          </div>
      {% else %}
      {% endif %}
          {% block content %}{% endblock %}
          <div class="bottom">
              <img src="{{ url_for('static', filename='images/regions.png') }}">
              <img src="{{ url_for('static', filename='images/regionh.png') }}">
              <img src="{{ url_for('static', filename='images/ku.png') }}">
            </div>
          </div>
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/bundle.js') }}"></script>
  </body>
</html>

Prototype/prototype/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <h1 style="border-bottom: 1px solid #000; padding-bottom: 15px; color: #02376a; font-size: 36px;">Login</h1>
                <div class="form-group">
                    {{ form.id.label(class="form-control-label") }}
                    {% if form.id.errors %}
                        {{ form.id(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.id.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.id(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">

        </small>
    </div>
{% endblock content %}

Prototype/prototype/templates/medicinkort.html
{% extends "layout.html" %}
{% block content %}
    {% if current_user.is_authenticated %}
    
    <h1 style="border-bottom: 1px solid #000; padding-bottom: 15px; color: #02376a; font-size: 36px;">Medicinkort</h1>

    {% for j in joined %}
    <div class="modul">
        <ul style="float:left; text-align:left;">
            <li>Ordineret: {{ j.prescribed }}</li>
            <li>Medicin: {{ j.medicine_name }}</li>
            <li>Medicin styrke: {{ j.medicine_concentration }}</li>
            <li>Behandling for: {{ j.illness }}</li>
            <li>Link til <a href="{{ j.link }}">patienthånbogen</a></li>
        </ul>
    </div>
    {% endfor %}

    {% endif %}
{% endblock content %}

Prototype/prototype/templates/receptfornyelse.html
{% extends "layout.html" %}
{% block content %}
    {% if current_user.is_authenticated %}
    <h1 style="border-bottom: 1px solid #000; padding-bottom: 15px; color: #02376a; font-size: 36px;">Receptfornyelse</h1>

    <h2 style="float:left; padding-left: 10px; margin-bottom: 5px;">Status på bestilt medicin</h2>

    {% for p in percs %}
    <div class="modul">
        <h3 style="float:left; padding-left: 3%; font-size: 24px;">{{ p.medicine_name }}</h3>
          <ul class="progressbar">
              {% if p.status == 'Ordered' %}
                <li class="active">Dato bestilt</li>
                <li>Modtaget af sekretær</li>
                <li>Godkendt af læge</li>
                <li>Klar til afhentning</li>
              {% elif p.status == 'Recieved' %}
                <li class="active">Dato bestilt</li>
                <li class="active">Modtaget af sekretær</li>
                <li>Godkendt af læge</li>
                <li>Klar til afhentning</li>
              {% elif p.status == 'Approved' %}
                <li class="active">Dato bestilt</li>
                <li class="active">Modtaget af sekretær</li>
                <li class="active">Godkendt af læge</li>
                <li>Klar til afhentning</li>
              {% elif p.status == 'Ready' %}
                <li class="active">Dato bestilt</li>
                <li class="active">Modtaget af sekretær</li>
                <li class="active">Godkendt af læge</li>
                <li class="active">Klar til afhentning</li>
              {% else %}
                <li>Dato bestilt</li>
                <li>Modtaget af sekretær</li>
                <li>Godkendt af læge</li>
                <li>Klar til afhentning</li>
              {% endif %}
          </ul>
    </div>
    {% endfor %}

  <h2 style="float:left; padding-left: 10px; margin-bottom: 5px;">Din medicin</h2>

    {% for p in percs %}
  <div class="modul_medicin">
      <div class="medicin_navn">
          <h2>{{ p.medicine_name }}</h2>
          <p>Styrke: {{ p.medicine_concentration }}</p>
          <p>Behandling for: {{ p.illness }}</p>
          <p>Fornyet sidst d. {{ p.renewal }}</p>
          <p>Udløber d. {{ p.expiration }}</p>
      </div>
      <div class="forny_knap">
        <div class="simple-button">
            <a href="{{ url_for('.renew', med_name=p.medicine_name, med_conc=p.medicine_concentration, illness=p.illness) }}" class="btn btn-primary">Forny</a>
        </div>
      </div>
  </div>

    {% endfor %}

    {% endif %}
{% endblock content %}